openapi: 3.0.0
tags:
  - name: Orders
post:
  description: None
parameters:
  - name: type
    in: query
    description: Type of the order (offer or bid)
    required: true
    type: string
  - name: price
    in: query
    description: Unit price of the order
    required: true
    type: number
  - name: quantity
    in: query
    description: Quantity of the order
    required: true
    type: integer
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          type:
            type: string
          price:
            type: number
          quantity:
            type: integer
responses:
    '201':
      description: Order received and recorded
    '406':
      description: Bad Request
    '500':
      description: Internal Server Error